### PR TITLE
Fix #13 Fix deserialize path for Vec<Option<Struct>>

### LINKED ISSUE #13: Add support for Vec<Option<Struct>>
This is mostly in place with https://github.com/DataEngineeringLabs/arrow2-derive/pull/10, but need to finish the deserialize path to check the valid bits, and do the right thing with the nested field iterators. Also need test cases.

### PR DESCRIPTION
**Pull request by ncpenke**
- Check valid bitmap when deserializing from struct array
- Fix bug in option blanket implementation
- Address review feedback to rename "unchecked" method to follow
  convention
- Always derive Debug for mutable arrays since it's a required trait for arrow2
- Update README

### CODE REVIEW

File: src/deserialize.rs [hunk 1]
```diff
@@ -218,9 +220,9 @@ where &'a dyn Array: FromArrow<T>
     }
 }
 
-/// Returns an iterator for elements from a [`arrow2::array::Array`]
+/// Internal helper to return an iterator for elements from a [`arrow2::array::Array`]. 
 /// Does not perform any schema checks.
-pub fn arrow_array_deserialize_unchecked_iter<'a, T>(b: &'a dyn arrow2::array::Array) -> arrow2::error::Result<impl Iterator<Item = T> + 'a>
+fn arrow_array_deserialize_iter<'a, T>(b: &'a dyn arrow2::array::Array) -> arrow2::error::Result<impl Iterator<Item = T> + 'a>
```
Comment (ncpenke) [inline src/deserialize.rs:225]: @jorgecarleitao I couldn't think of a better name, so I removed the "unchecked" and made this private for now (since it's only used internal to this file). We can come up with a better name if this becomes a public API. I think we should probably check the schema for all public methods anyways.
